import streamlit as st
import requests
from PIL import Image
from datetime import datetime
import time
import os
import random 
import numpy as np 






# Start Here Login system API generated by AI


# --- Auth API base (points to your backend auth routes) ---
AUTH_BASE_URL = os.getenv("AUTH_URL", "http://localhost:3000/api/auth")

# --- Session state for auth ---
if "api" not in st.session_state:                  # requests.Session to persist cookies
    st.session_state.api = requests.Session()
if "user" not in st.session_state:                 # logged-in user payload from backend
    st.session_state.user = None
if "auth_msg" not in st.session_state:             # last auth message
    st.session_state.auth_msg = ""





def auth_me():
    """Fetch current user from backend session."""
    try:
        r = st.session_state.api.get(f"{AUTH_BASE_URL}/me", timeout=6)
        data = r.json()
        st.session_state.user = data.get("user")
    except Exception as e:
        st.session_state.auth_msg = f"Auth check failed: {e}"

def auth_signup(user_id: str, password: str):
    """Sign up and (optionally) auto-login."""
    try:
        r = st.session_state.api.post(
            f"{AUTH_BASE_URL}/signup",
            json={"user_id": user_id, "password": password},
            timeout=8,
        )
        data = r.json()
        if r.ok and data.get("user"):
            st.session_state.user = data["user"]
            st.session_state.auth_msg = f"Welcome, {data['user']['user_id']}! Your account was created."
            return True
        else:
            st.session_state.auth_msg = data.get("error", "Signup failed.")
            return False
    except Exception as e:
        st.session_state.auth_msg = f"Signup failed: {e}"
        return False

def auth_login(user_id: str, password: str):
    """Log in existing user."""
    try:
        r = st.session_state.api.post(
            f"{AUTH_BASE_URL}/login",
            json={"user_id": user_id, "password": password},
            timeout=8,
        )
        data = r.json()
        if r.ok and data.get("user"):
            st.session_state.user = data["user"]
            st.session_state.auth_msg = f"Logged in as {data['user']['user_id']}."
            return True
        else:
            st.session_state.auth_msg = data.get("error", "Login failed.")
            return False
    except Exception as e:
        st.session_state.auth_msg = f"Login failed: {e}"
        return False

def auth_logout():
    """Log out and clear session."""
    try:
        st.session_state.api.post(f"{AUTH_BASE_URL}/logout", json={}, timeout=6)
    except Exception:
        pass
    finally:
        st.session_state.user = None
        st.session_state.auth_msg = "You’ve been logged out."



# End Here






# Set the page configuration (must be the first Streamlit command)
st.set_page_config(
    page_title="SnapStyle - Smart Wardrobe Assistant",
    layout="wide",
    initial_sidebar_state="collapsed",
    page_icon="🧥",
)

# API Configuration (Assuming a backend API for processing will be used)
API_BASE_URL = os.getenv("API_URL", "http://localhost:8000/snapstyle")

# Initialize session state
if "wardrobe_items" not in st.session_state:
    # Example item for testing. In production, this would be an empty list.
    st.session_state.wardrobe_items = [
        {"name": "Navy Blazer", "category": "Jacket", "color": "Navy", "texture": "Wool", "style_score": 90.5, "embedding": np.round(np.random.rand(5), 2).tolist()},
        {"name": "White T-shirt", "category": "T-shirt", "color": "White", "texture": "Cotton", "style_score": 88.0, "embedding": np.round(np.random.rand(5), 2).tolist()},
        {"name": "Dark Wash Jeans", "category": "Jeans", "color": "Blue", "texture": "Denim", "style_score": 85.0, "embedding": np.round(np.random.rand(5), 2).tolist()},
        {"name": "Brown Loafers", "category": "Shoes", "color": "Brown", "texture": "Leather", "style_score": 92.1, "embedding": np.round(np.random.rand(5), 2).tolist()},
        {"name": "Gray Slacks", "category": "Jeans", "color": "Gray", "texture": "Wool", "style_score": 93.3, "embedding": np.round(np.random.rand(5), 2).tolist()},
        {"name": "Silk Scarf", "category": "Accessory", "color": "Red", "texture": "Silk", "style_score": 80.0, "embedding": np.round(np.random.rand(5), 2).tolist()},
    ]
if "current_outfit_index" not in st.session_state:
    st.session_state.current_outfit_index = 0
if "recommended_outfits" not in st.session_state:
    st.session_state.recommended_outfits = []
if "user_prompt" not in st.session_state:
    st.session_state.user_prompt = "e.g. Formal look for a presentation."
if "is_loading" not in st.session_state:
    st.session_state.is_loading = False


# Add loading state management (Kept as is)
def show_loading_spinner(message="Loading..."):
    """Show a professional loading spinner"""
    st.markdown(
        f"""
    <div style="display: flex; justify-content: center; align-items: center; padding: 2rem;">
        <div style="
            border: 4px solid #f3f3f3;
            border-top: 4px solid #ff6b6b;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            animation: spin 1s linear infinite;
            margin-right: 1rem;
        "></div>
        <span style="color: #666; font-weight: 500;">{message}</span>
    </div>
    <style>
        @keyframes spin {{
            0% {{ transform: rotate(0deg); }}
            100% {{ transform: rotate(360deg); }}
        }}
    </style>
    """,
        unsafe_allow_html=True,
    )


# Professional CSS (Kept as is)
st.markdown(
    """
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

  :root{
    /* Menswear palette */
    --bg-1:#f5f6f7;          /* near-white */
    --bg-2:#e9eef2;          /* light steel */
    --ink:#101418;           /* charcoal */
    --muted:#6b7280;         /* slate */
    --card:#ffffff;          /* white */
    --line:#e5e7eb;          /* light border */
    --accent:#0f2a4a;        /* deep navy */
    --accent-2:#1f3f6e;      /* steel navy */
    --accent-3:#2b4f88;      /* indigo navy */
    --highlight:#c08400;     /* amber/gold */
    --highlight-2:#975a16;   /* warm tan */
    --shadow:0 16px 40px rgba(16,20,24,0.10);
    --shadow-hover:0 20px 50px rgba(16,20,24,0.14);
    --radius-xl:20px;
    --radius-lg:12px;
  }

  /* Global */
  .stApp{
    background: linear-gradient(135deg, var(--bg-1) 0%, var(--bg-2) 60%, #f7f9fb 100%);
    font-family:'Inter',sans-serif;
    color:var(--ink);
  }
  .main .block-container{padding-top:0rem;padding-bottom:2rem;max-width:1200px;}

  /* Hide Streamlit chrome & noisy UI */
  #MainMenu, footer, header, [data-testid="stToolbar"], .stDeployButton,
  [data-testid="stDecoration"], .stActionButton, .stAlert, .stWarning,
  [data-testid="stNotification"], .stToast, [data-testid="stStatusWidget"]{display:none !important;}

  /* Title */
  .logo-container{text-align:center;margin:2rem 0;}
  .app-title{
    color:var(--ink);font-size:2.6rem;font-weight:700;margin:1rem 0 .5rem 0;letter-spacing:-.02em;
  }
  .app-subtitle{
    color:var(--muted);font-size:1.05rem;font-weight:500;margin-bottom:0;
  }

  /* Tabs */
  .stTabs [data-baseweb="tab-list"]{
    gap:8px;background:rgba(15,42,74,0.06);
    border-radius:16px;padding:8px;backdrop-filter:blur(10px);
    border:1px solid rgba(31,63,110,0.12);
  }
  .stTabs [data-baseweb="tab"]{
    color:var(--ink);background:transparent;border-radius:12px;font-weight:600;
    padding:12px 24px;transition:.25s ease;
  }
  .stTabs [aria-selected="true"]{
    background:linear-gradient(135deg, rgba(31,63,110,.20), rgba(43,79,136,.18)) !important;
    color:var(--ink) !important;box-shadow:0 4px 12px rgba(31,63,110,.18);
    border:1px solid rgba(31,63,110,.22);
  }

  /* Cards */
  .profile-card{
    background:var(--card);border-radius:var(--radius-xl);padding:0;margin:2rem auto;
    max-width:520px;box-shadow:var(--shadow);overflow:hidden;
    transition:transform .25s ease, box-shadow .25s ease;
    border:1px solid var(--line);
  }
  .profile-card:hover{transform:translateY(-4px);box-shadow:var(--shadow-hover);}
  .card-image{width:100%;height:400px;object-fit:cover;background:linear-gradient(45deg,#f3f4f6,#e5e7eb);
    display:flex;align-items:center;justify-content:center;font-size:4rem;color:#b8c0cc;}
  .card-content{padding:24px;}

  .outfit-name{
    font-size:2.1rem;font-weight:800;color:var(--ink);margin-bottom:.5rem;letter-spacing:-.01em;text-align:center;
  }
  .outfit-style{
    font-size:1.05rem;color:var(--muted);margin-bottom:1.25rem;font-weight:600;text-align:center;
  }

  .item-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:20px 0;}
  .stat-item{
    background:#f8fafc;padding:12px;border-radius:var(--radius-lg);text-align:center;
    border:1px solid var(--line);transition:background .2s ease;
  }
  .stat-label{font-weight:700;color:#4b5563;font-size:.78rem;text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px;}
  .stat-value{color:var(--highlight);font-size:1.1rem;font-weight:800;}

  .item-description{
    font-style:italic;color:#4b5563;line-height:1.6;margin:20px 0;font-size:1rem;
    background:#f8fafc;padding:16px;border-radius:var(--radius-lg);border-left:4px solid var(--accent-3);
  }

  /* Quality Score */
  .compatibility-score{
    font-size:2.6rem;font-weight:900;
    background:linear-gradient(135deg, var(--highlight), var(--highlight-2));
    -webkit-background-clip:text;-webkit-text-fill-color:transparent;
    text-align:center;margin:12px 0;letter-spacing:-.02em;
  }

  /* Buttons */
  .stButton > button{
    background:linear-gradient(135deg, var(--accent), var(--accent-3)) !important;
    color:white !important;border:none !important;border-radius:12px !important;
    font-weight:700 !important;font-family:'Inter',sans-serif !important;
    padding:12px 24px !important;transition:.25s ease !important;
    box-shadow:0 4px 12px rgba(15,42,74,.25) !important;border:1px solid rgba(255,255,255,.06);
  }
  .stButton > button:hover{transform:translateY(-2px) !important;box-shadow:0 8px 20px rgba(15,42,74,.35) !important;}

  /* Metrics */
  .metric-card{
    background:var(--card);border:1px solid var(--line);border-radius:16px;padding:20px;text-align:center;
    box-shadow:0 6px 18px rgba(16,20,24,0.06);
  }

  /* Subtle info banners */
  .content-card h2{color:var(--ink);font-weight:800;}
  .content-card p{color:var(--muted);}
</style>

""",
    unsafe_allow_html=True,
)



def load_banner():
    """Load and display the logo at the top of the page (Updated for SnapStyle)"""
    st.markdown('<div class="logo-container">', unsafe_allow_html=True)

    # Fallback with beautiful typography for SnapStyle
    st.markdown(
        '<h1 class="app-title"> 🧥 SnapStyle - Smart Wardrobe Assistant</h1>', unsafe_allow_html=True
    )
    st.markdown(
        '<p class="app-subtitle">Your AI-powered guide to effortless everyday dressing.</p>',
        unsafe_allow_html=True,
    )

    st.markdown("</div>", unsafe_allow_html=True)


def digitize_closet_form():
    """Create clothing item upload form with image and metadata, now reflecting YOLOv8/Meta Model"""
    st.markdown(
        """
    <div class="content-card">
        <h2 style="color: #1a1a1a; margin-bottom: 0.5rem; font-weight: 700;">📸 Digitize Your Closet (Layer 1)</h2>
        <p style="color: #666; margin-bottom: 2rem; font-size: 1.1rem;">Upload a photo of your clothing item for **YOLOv8** object detection and **Meta** feature extraction.</p>
    </div>
    """,
        unsafe_allow_html=True,
    )

    with st.form("item_upload_form"):
        col1, col2 = st.columns([1, 1])

        with col1:
            st.subheader("🖼️ Item Photo Upload")
            uploaded_file = st.file_uploader(
                "Choose an image of your clothing item",
                type=["png", "jpg", "jpeg"],
                help="The clearer the photo, the better the AI can identify features (e.g., color, texture).",
            )

            if uploaded_file is not None:
                image = Image.open(uploaded_file)
                st.image(image, caption="Uploaded Item Photo", use_container_width=True)
                # Placeholder for the single item selection if the image contains a whole closet
                st.info("💡 **YOLOv8** would detect and crop the *single* item for feature extraction.")

        with col2:
            st.subheader("🏷️ Item Details (Verification)")

            # Basic Info (User input for potential verification/labeling)
            item_name = st.text_input("Item Name", placeholder="e.g., Blue Denim Jacket")
            category = st.selectbox(
                "Clothing Category (YOLOv8 output verification)",
                [
                    "T-shirt",
                    "Hoodie",
                    "Sweater",
                    "Jeans",
                    "Skirt",
                    "Dress",
                    "Jacket",
                    "Coat",
                    "Shoes",
                    "Accessory",
                ],
            )
            

            # st.markdown("---")
            # st.caption("The AI will extract **visual features** (embeddings) for similarity search.")
            
        # Submit button
        submitted = st.form_submit_button("⬆️ Upload Item & Analyze (Layer 1)", use_container_width=True)

        if submitted:
            if uploaded_file and item_name and category:
                # 1. Simulate AI Processing
                st.session_state.is_loading = True
                show_loading_spinner("Running YOLOv8 and extracting item embeddings...")
                time.sleep(2) # Simulate network/processing delay
                st.session_state.is_loading = False
                
                # 2. Simulate AI Output & Verification
                verified_category = category 
                style_score = round(random.uniform(70.0, 95.0), 1)
                
                # Simulate Meta model's embedding output (5 dimensions for simplicity)
                embedding_vector = np.round(np.random.rand(5), 4).tolist()

                # Store item data
                item_data = {
                    "name": item_name,
                    "category": verified_category,
                    "color": color,
                    "texture": texture,
                    "uploaded_at": datetime.now().isoformat(),
                    "style_score": style_score,
                    "embedding": embedding_vector,
                    # "uploaded_file": uploaded_file, # Omitted for simplicity
                }
                st.session_state.wardrobe_items.append(item_data)

                # Display AI Feedback
                st.success(f"✅ Item **'{item_name}'** successfully digitized and added to your virtual closet!")
                st.info(f"**Layer 1: YOLOv8 Detection & Meta Embeddings**")
                st.markdown(f"* **Category Label:** `{verified_category}` (YOLOv8 Verification)")
                st.markdown(f"* **Extracted Embeddings (Meta Model):** `{embedding_vector}` (Used for ANN Search)")
                st.markdown(f"* **General Style Score:** **{style_score}%** (Initial quality rating)")
                st.balloons()
            else:
                st.error("Please provide a photo, item name, and category.")
                
            # Clear input fields after submission (Not directly possible with Streamlit's default widgets without keys/callback)
            # st.experimental_rerun()


def digitize_closet_form():
    st.markdown(
        """
    <div class="content-card">
        <h2 style="color: #1a1a1a; margin-bottom: 0.5rem; font-weight: 700;">📸 Digitize Your Closet (Layer 1)</h2>
        <p style="color: #666; margin-bottom: 2rem; font-size: 1.1rem;">
            Upload a clothing photo — SnapStyle will detect your items (YOLOv8) and extract embeddings.
        </p>
    </div>
    """,
        unsafe_allow_html=True,
    )

    # -------------------------
    # FORM UI
    # -------------------------
    with st.form("item_upload_form"):
        uploaded_file = st.file_uploader(
            "Upload clothing item image",
            type=["png", "jpg", "jpeg"],
        )

        item_name = st.text_input("Item Name (optional)")
        submitted = st.form_submit_button("⬆️ Upload & Analyze", use_container_width=True)

    # -------------------------
    # FORM SUBMISSION
    # -------------------------
    if submitted:
        if uploaded_file is None:
            st.error("Please upload an image.")
            return
        
        st.session_state.uploaded_file = uploaded_file
        st.session_state.item_name = item_name
        st.session_state.is_loading = True
        st.rerun()

    # -------------------------
    # PIPELINE PROCESSING
    # -------------------------
    if st.session_state.get("is_loading", False):
        show_loading_spinner("Running YOLO detection & embedding pipeline...")

        try:
            file = st.session_state.uploaded_file
            files = {
                "file": (file.name, file.getvalue(), file.type)
            }

            api_url = "http://snapstyle-backend:8000/yolo/embed"
            response = requests.post(api_url, files=files)

            if response.status_code != 200:
                st.session_state.is_loading = False
                st.error(f"API Error: {response.text}")
                return

            data = response.json()
            st.session_state.is_loading = False

            # Save detection results in session_state
            st.session_state.detected_items = data["items"]

            st.success(f"Detected {data['num_items']} item(s). Added to your closet!")

            # Add to wardrobe
            for item in data["items"]:
                st.session_state.wardrobe_items.append({
                    "name": st.session_state.item_name or item["category"],
                    "category": item["category"],
                    "color": "Unknown",
                    "texture": "Unknown",
                    "uploaded_at": datetime.now().isoformat(),
                    "style_score": round(random.uniform(75, 95), 1),
                    "embedding_path": item["embedding_path"],
                    "crop_path": item["crop_path"],
                })

            st.rerun()

        except Exception as e:
            st.session_state.is_loading = False
            st.error(f"Upload failed: {e}")
            st.rerun()

    # -------------------------
    # DISPLAY DETECTED YOLO CROPS
    # -------------------------
    if "detected_items" in st.session_state:
        st.markdown("### ✂️ YOLO Cropped Items:")

        desired_categories = ["top", "bottom", "shoes"]

        for item in st.session_state.detected_items:
            if item["category"] in desired_categories:
                st.image(item["crop_path"], caption=item["category"])





def display_outfit_card(outfit):
    """Display a professional outfit recommendation card"""
    # Center the card
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        # Card container
        st.markdown('<div class="profile-card">', unsafe_allow_html=True)

        # Outfit Title and Style
        st.markdown('<div class="card-content" style="text-align: center;">', unsafe_allow_html=True)
        st.markdown(f'<h1 class="outfit-name">{outfit["title"]}</h1>', unsafe_allow_html=True)
        st.markdown(f'<p class="outfit-style">**Style Label:** {outfit["style_label"]} | **Occasion Tag:** {outfit["occasion_tag"]}</p>', unsafe_allow_html=True)

        # Quality Score
        st.markdown(f"""
            <div class="compatibility-score">
                {outfit["quality_score"]}%
            </div>
            <div style="text-align: center; color: #555; font-weight: 600; margin-bottom: 20px;">
                Layer 4: AI Quality Score
            </div>
        """, unsafe_allow_html=True)

        # Outfit Items
        st.subheader("👚 Outfit Components (ANN Search Results):")
        
        for item in outfit["items"]:
            # Display components including color/texture
            st.markdown(
                f"""
                <div class="stat-item" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                    <div style="font-weight: 600; color: #1a1a1a;">{item['category']}</div>
                    <div style="color: #666; font-size: 0.9rem;">{item['color']} | {item['texture']}</div>
                    <div style="color: #ff6b6b; font-weight: 700;">{item['name']}</div>
                </div>
                """, unsafe_allow_html=True
            )
        
        # Rationale/Coherence
        st.subheader("✨ Rationale (Style Coherence & Color Harmony):")
        st.markdown(
            f"""
        <div style="background: #f8f9fa; padding: 16px; border-radius: 12px; margin: 10px 0; border-left: 4px solid #ff6b6b;">
            <em style="color: #555; font-size: 1rem; line-height: 1.4;">{outfit["rationale"]}</em>
        </div>
        """,
            unsafe_allow_html=True,
        )

        st.markdown("</div>", unsafe_allow_html=True) # Close card-content
        st.markdown("</div>", unsafe_allow_html=True) # Close card


def outfit_planner_interface():
    """Interface for generating and viewing outfit recommendations"""
    st.markdown(
        """
    <div class="content-card">
        <h2 style="color: #1a1a1a; margin-bottom: 0.5rem; font-weight: 700;">✨ Outfit Planner (Layers 2-4)</h2>
        <p style="color: #666; margin-bottom: 1rem; font-size: 1.1rem;">Input a prompt to generate tailored outfits based on your digitized closet.</p>
    </div>
    """,
        unsafe_allow_html=True,
    )
    
    # User Prompt & Generation - Changed to text input for BERT/ANN simulation
    with st.container():
        st.subheader("📝 Text Prompt (Driven by BERT/ANN)")
        
        # Text input for the user's desired style/occasion
        prompt_input = st.text_input(
            "Describe the look you want to achieve:",
            value=st.session_state.user_prompt,
            placeholder="e.g., Formal interview look for rainy weather",
            key="style_prompt_text"
        )
        
        col_button = st.columns([1, 1, 1])[1]
        with col_button:
            if st.button("🚀 Generate Outfits (Run Layer 2-4)", use_container_width=True):
                st.session_state.user_prompt = prompt_input
                st.session_state.current_outfit_index = 0 # Reset index when generating new outfits
                generate_outfits(st.session_state.user_prompt)

    st.markdown("---")

    # Display Results
    if st.session_state.is_loading:
        # Loading spinner is already displayed inside generate_outfits, just wait
        pass
    elif not st.session_state.recommended_outfits:
        st.info("Upload items in the 'Digitize Closet' tab, describe your look, and click 'Generate Outfits' to see recommendations.")
        st.markdown(f"**Items Currently in Closet:** {len(st.session_state.wardrobe_items)}")
        if st.session_state.wardrobe_items:
             st.dataframe(
                [{"Item": item['name'], "Category": item['category'], "Score": f"{item['style_score']}%"} for item in st.session_state.wardrobe_items],
                use_container_width=True
            )
    else:
        num_outfits = len(st.session_state.recommended_outfits)
        st.success(f"✅ Found **{num_outfits}** high-scoring outfits for '{st.session_state.user_prompt}' style!")
        st.caption(f"Note: {num_outfits} is the number of suggestions remaining after the Layer 4 Scoring System filtered out low-ranked options.")
        
        # Display the current outfit
        current_outfit = st.session_state.recommended_outfits[st.session_state.current_outfit_index]
        display_outfit_card(current_outfit)

        # Navigation Buttons (Prev/Next)
        col1, col2, col3 = st.columns([1, 1, 1])
        
        with col1:
            if st.button("⬅️ Previous Outfit", disabled=(st.session_state.current_outfit_index == 0), use_container_width=True):
                st.session_state.current_outfit_index -= 1
                st.rerun()

        with col3:
            if st.button("Next Outfit ➡️", disabled=(st.session_state.current_outfit_index >= num_outfits - 1), use_container_width=True):
                st.session_state.current_outfit_index += 1
                st.rerun()

        # Progress indicator
        progress_text = f"Outfit {st.session_state.current_outfit_index + 1} of {num_outfits}"
        st.progress((st.session_state.current_outfit_index + 1) / num_outfits, text=progress_text)


# --- Main Application (Kept as is) ---

def main():
    """Main app function"""
    load_banner()

    # Navigation
    tab1, tab2, tab3 = st.tabs(["🏠 Home", "📸 Digitize Closet", "✨ Outfit Planner"])

    with tab1:
        # Welcome content (Updated for SnapStyle)
        st.markdown(
            '<h2 style="color: #1a1a1a; margin: 2rem 0 1rem 0; font-weight: 700; text-align: center;">Welcome to SnapStyle! 🧥</h2>',
            unsafe_allow_html=True,
        )

        st.markdown(
            """
        <p style="font-size: 1.1rem; color: #555; line-height: 1.6; margin-bottom: 2rem; text-align: center;">
            This is a ML app for fashion style assistance. The user can upload their items in closet and get a recommendation based on the prompt they enter and the gerenral style we provided.
            Enjoy :)
        </p>
        """,
            unsafe_allow_html=True,
        )

        st.markdown(
            '<h3 style="color: #333; margin-bottom: 1rem; font-weight: 600;">How Our AI Works (4-Layer System):</h3>',
            unsafe_allow_html=True,
        )
        st.markdown(
            """
        <div style="margin-left: 1rem; margin-bottom: 2rem;">
            <p style="margin: 0.5rem 0; color: #555;"><strong>Layer 1 (Input/Storage):</strong> **YOLOv8** identifies items. **Meta's Embedding Model** extracts features. Items are stored for **ANN searches**.</p>
            <p style="margin: 0.5rem 0; color: #555;"><strong>Layer 2 (Generation):</strong> **BERT/ANN** processes your text prompt. **ANN Searches** find compatible items. **20-50** combinations generated.</p>
            <p style="margin: 0.5rem 0; color: #555;"><strong>Layer 3 (Classification):</strong> Predicts each combination's **Style Label** and **Occasion Tag**.</p>
            <p style="margin: 0.5rem 0; color: #555;"><strong>Layer 4 (Scoring):</strong> Evaluates outfits using **visual & semantic features** (color harmony, texture coherence) to assign a **Quality Score** and filter out low-ranked suggestions.</p>
        </div>
        """,
            unsafe_allow_html=True,
        )

        # Metrics (Adjusted)
        col1, col2, col3 = st.columns(3)
        with col1:
            st.markdown(
                f"""
            <div class="metric-card">
                <h3 style="color: #ff6b6b; font-size: 2rem; margin: 0; font-weight: 700;">{len(st.session_state.wardrobe_items)}</h3>
                <p style="color: #555; margin: 0.5rem 0 0 0; font-weight: 500;">Items in Closet</p>
            </div>
            """,
                unsafe_allow_html=True,
            )
        with col2:
            st.markdown(
                """
            <div class="metric-card">
                <h3 style="color: #ff6b6b; font-size: 2rem; margin: 0; font-weight: 700;">YOLOv8 / Meta</h3>
                <p style="color: #555; margin: 0.5rem 0 0 0; font-weight: 500;">Detection & Embeddings</p>
            </div>
            """,
                unsafe_allow_html=True,
            )
        with col3:
            st.markdown(
                """
            <div class="metric-card">
                <h3 style="color: #ff6b6b; font-size: 2rem; margin: 0; font-weight: 700;">BERT / ANN</h3>
                <p style="color: #555; margin: 0.5rem 0 0 0; font-weight: 500;">Text & Compatibility</p>
            </div>
            """,
                unsafe_allow_html=True,
            )

            
    with tab2:
        # --- Account (Sign up / Log in) ---
        st.markdown(
            '<h3 style="color:#1a1a1a; margin-top:0.5rem; font-weight:700;">Account</h3>',
            unsafe_allow_html=True,
        )

        if st.session_state.user:
            # Logged-in view
            st.success(f"Signed in as **{st.session_state.user.get('user_id','user')}**")
            colA, colB = st.columns([1, 2])
            with colA:
                if st.button("Log out"):
                    auth_logout()
                    st.rerun()
            with colB:
                st.caption("You’re authenticated. Outfit generation and closet actions can be associated with your account.")

        else:
            # Not logged in: show Sign up / Log in tabs
            subtab_signup, subtab_login = st.tabs(["🆕 Sign up", "🔑 Log in"])

            with subtab_signup:
                with st.form("signup_form", clear_on_submit=False):
                    su_user_id = st.text_input("Create Your User ID", key="su_user_id", placeholder="gu123")
                    su_pw = st.text_input("Password (8+ chars)", key="su_pw", type="password")
                    su_btn = st.form_submit_button("Create account")
                if su_btn:
                    if su_user_id and su_pw:
                        ok = auth_signup(su_user_id.strip().lower(), su_pw)
                        if ok:
                            st.success(st.session_state.auth_msg)
                            st.rerun()
                        else:
                            st.error(st.session_state.auth_msg)
                    else:
                        st.error("Please enter an user_id and password.")

            with subtab_login:
                with st.form("login_form", clear_on_submit=False):
                    li_user_id = st.text_input("User ID", key="li_user_id", placeholder="Your User ID here")
                    li_pw = st.text_input("Password", key="li_pw", type="password")
                    li_btn = st.form_submit_button("Log in")
                if li_btn:
                    if li_user_id and li_pw:
                        ok = auth_login(li_user_id.strip().lower(), li_pw)
                        if ok:
                            st.success(st.session_state.auth_msg)
                            st.rerun()
                        else:
                            st.error(st.session_state.auth_msg)
                    else:
                        st.error("Please enter an user_id and password.")

        # Optional: subtle status line
        if st.session_state.auth_msg and not st.session_state.user:
            st.caption(st.session_state.auth_msg)

        digitize_closet_form()

    with tab3:
        outfit_planner_interface()


if __name__ == "__main__":
    main()